#!/usr/bin/env python3
from rich.console import Console

console = Console()

console.clear()


console.print("[red] _______  _______  _______ ")
console.print("[orange3](  ____ )(  ____ \(  ___  )")
console.print("[yellow]| (    )|| (    \/| (   ) |")
console.print("[green]| (____)|| (_____ | (___) |")
console.print("[blue]|  _____)(_____  )|  ___  |")
console.print("[purple]| (            ) || (   ) |")
console.print("[red]| )      /\____) || )   ( |")
console.print("[orange3]|/       \_______)|/     \|")
console.print("")
console.print("[bold blue]a new way to found new [bold purple]flavours[/bold purple] and [bold purple]plugins")                           

