#!/usr/bin/env python3

# from funcs.interactiveFuncs import *
import textwrap
import argparse
from funcs.init import init
from funcs.run import run
from funcs.fetch import fetch
from funcs.install import install
from funcs.ps import ps
from funcs.rn import rn
from funcs.rm import rm

# argparse
parser = argparse.ArgumentParser(prog='DesktopStudio',
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 description=textwrap.dedent('''\

        Avaliable Actions

        ----------------------------------------------------------------

        init        creates a new project
        run         run a script on the project
        fetch       fetch the online keyrings to the latest versions
        install     install an avariable package
        ps          shows the current installed flavours
        rn          run a plugin
        rm          unistall a plugin or a flavour

                                '''))

parser.add_argument('action')
parser.add_argument('-s', '--script')                        # positional argument
parser.add_argument('-p', '--package')                        # positional argument
parser.add_argument('-v', '--verbose', action='store_true')  # on/off flag

args = parser.parse_args()

if __name__ == "__main__":
    if args.action == "init":
        init()
    if args.action == "run":
        run(args.script)
    if args.action == "fetch":
        fetch()
    if args.action == "install":
        install(args.package)
    if args.action == "ps":
        ps()
    if args.action == "rn":
        rn(args.script)
    if args.action == "rm":
        rm(args.package)