#!/usr/bin/env python3

import argparse
from funcs.init import init
from funcs.run import run
from funcs.fetch import fetch
from funcs.install import install
from funcs.ps import ps

# argparse
parser = argparse.ArgumentParser(prog='DesktopStudio', description='A docker-based studio for your linux configs and enviroments', epilog='by s7lver')

parser.add_argument('action')
parser.add_argument('-s', '--script')                        # positional argument
parser.add_argument('-p', '--package')                        # positional argument
parser.add_argument('-v', '--verbose', action='store_true')  # on/off flag

args = parser.parse_args()

if __name__ == "__main__":
    if args.action == "init":
        init()
    if args.action == "run":
        run(args.script)
    if args.action == "fetch":
        fetch()
    if args.action == "install":
        install(args.package)
    if args.action == "ps":
        ps()