[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x24
autostart=true
autorestart=true
priority=1

[program:gnome-session]
command=/usr/bin/gnome-session
environment=DISPLAY=":1"
autostart=true
autorestart=true
priority=2

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -rfbport 5901 -passwd vncpassword
autostart=true
autorestart=true
priority=3
